#! python
"""
ddsop.py

This script adds operation commands to dds service.
These command will load the same configurations generated by dds command.

Usage: ddsop.py [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  delete_all  Delete all datasets imported before.
  delete_one  Delete a dataset.
  import_all  Trigger a background task of importing all datasets in a...
  import_one  Trigger a background task of importing one dataset.
  lpexport    Export the labels of a label project.
  shell       Enter a Python interpreter shell with all dds configs loaded.
  useradd     Add a user by username.
  userban     Ban a user by username.
  userdel     Delete a user by username.
  useredit    Edit user attributes for a user by username.
  userreset   Reset password for a user by username.
  userunban   Unban a user by username.
"""

from deepdataspace.scripts import ddsop

if __name__ == "__main__":
    ddsop()
