name: Sync Dev to Private Repo
on:
  push:
    branches:
      - dev
jobs:
  merge-and-rebase:
    if: github.repository_owner == 'IDEA-Research'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Private Repo
        uses: actions/checkout@v2
        with:
          repository: deepdataspace/deepdataspace
          ref: dev
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}

      - name: Add Public Remote
        run: |
          git remote add public https://github.com/IDEA-Research/deepdataspace.git

      - name: Rebase Private Repo
        run: |
          git pull public dev --rebase

      - name: Push Private Repo
        run: |
          git push
